DIROBJ := obj/
DIREXE := exec/
DIRHEA := include/
DIRSRC := src/

CFLAGS := -I$(DIRHEA) -c -Wall -ansi
LDFLAGS := -lglut -lGLU -lGL
CC := gcc

all: dirs helloOpenGL test

dirs:
	mkdir -p $(DIROBJ) $(DIREXE)

helloOpenGL: $(DIROBJ)helloOpenGL.o 
	$(CC) -o $(DIREXE)$@ $^ $(LDFLAGS)

test: $(DIROBJ)test.o 
	$(CC) -o $(DIREXE)$@ $^ $(LDFLAGS)

ejercicio1:$(DIROBJ)ejercicio1.o 
	$(CC) -o $(DIREXE)$@ $^ $(LDFLAGS)
	./$(DIREXE)ejercicio1
	

$(DIROBJ)%.o: $(DIRSRC)%.c
	$(CC) $(CFLAGS) $^ -o $@

clean: 
	rm -rf *~ core $(DIROBJ) $(DIREXE) $(DIRHEA)*~ $(DIRSRC)*~
